/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-31 12:46:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.accountingapp.model.User;

public final class businesspartners_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.accountingapp.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/headerandmenu.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<!-- MAIN CONTENT START -->\r\n");
      out.write("<link href=\"../include/css/dataTables.bootstrap4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"../include/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"../include/js/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\tvar sendAjaxBP;\r\n");
      out.write("\t\tvar getBusinessPartners;\r\n");
      out.write("\t\tvar fillBusinessPartnersTable;\r\n");
      out.write("\t\tvar businessPartnerTable = undefined;\r\n");
      out.write("\t\tvar openUpdateModal;\r\n");
      out.write("\t\tvar currentRowData;\r\n");
      out.write("\t\tvar deleteBusinessPartner;\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\tsendAjaxBP = function(jsonreq,url,async,type){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\ttype : type,\r\n");
      out.write("\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\tdata : JSON.stringify(jsonreq),\r\n");
      out.write("\t\t\t\t\tcontentType : 'application/json',\r\n");
      out.write("\t\t\t\t\tmimeType : 'application/json',\r\n");
      out.write("\t\t\t\t\tasync : async,\r\n");
      out.write("\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\tif(typeof data == 'string' && data.includes(\"redirect_url\")){\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href = data.split(\":\")[1];\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tif(jsonreq.params[0] == \"save_bp\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(jsonreq.params[2] == \"update\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(\"Güncelleme işlemi başarılı.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else if(jsonreq.params[2] == \"save\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(\"Ekleme işlemi başarılı.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#businessPartnerModal').modal('hide');\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgetBusinessPartners();\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(jsonreq.params[0] == \"get_all_bp\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tfillBusinessPartnersTable(data);\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(data)\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif(jsonreq.params[0] == \"delete_bp\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert('Silme işemi başarılı.')\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgetBusinessPartners();\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert('Bir hata oluştu!')\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},error : function(e){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t            \talert('ERROR '+e.responseText)\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#newBusinessPartnerBtn').on('click',function(){\r\n");
      out.write("\t\t\t\t$('#bpId').val('');\r\n");
      out.write("\t\t\t\t$('#bpName').val('');\r\n");
      out.write("\t\t\t\t$('#bpTelNo').val('');\r\n");
      out.write("\t\t\t\t$('#bpMail').val('');\r\n");
      out.write("\t\t\t\t$('#bpAddress').val('');\r\n");
      out.write("\t\t\t\t$('#bpNote').val('');\r\n");
      out.write("\t\t\t\t$('#businessPartnerModalLabel').text('Müşteri Ekleme - Yeni Kayıt');\r\n");
      out.write("\t\t\t\t$('#businessPartnerModal').modal('show');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#updateBusinessPartnerBtn').on('click',function(){\r\n");
      out.write("\t\t\t\topenUpdateModal();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#businessPartnerSaveBtn').on('click',function(){\r\n");
      out.write("\t\t\t\tvar bpObj = new Object();\r\n");
      out.write("\t\t\t\tif($('#bpId').val().length > 0){\r\n");
      out.write("\t\t\t\t\tbpObj.id = $('#bpId').val();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tbpObj.partnerName = $('#bpName').val();\r\n");
      out.write("\t\t\t\tbpObj.telno = $('#bpTelNo').val();\r\n");
      out.write("\t\t\t\tbpObj.email = $('#bpMail').val();\r\n");
      out.write("\t\t\t\tbpObj.note = $('#bpNote').val();\r\n");
      out.write("\t\t\t\tbpObj.address = $('#bpAddress').val();\r\n");
      out.write("\t\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\t\tjsonreq.params[0] = \"save_bp\";\r\n");
      out.write("\t\t\t\tjsonreq.params[1] = JSON.stringify(bpObj);\r\n");
      out.write("\t\t\t\tif($('#bpId').val().length > 0){\r\n");
      out.write("\t\t\t\t\tbpObj.id = $('#bpId').val();\r\n");
      out.write("\t\t\t\t\tjsonreq.params[2] = \"update\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tjsonreq.params[2] = \"save\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tsendAjaxBP(jsonreq,\"/Accounting/AccountingServlet\",true,\"POST\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#deleteBusinessPartnerBtn').on('click',function(){\r\n");
      out.write("\t\t\t\tdeleteBusinessPartner();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\topenUpdateModal = function(){\r\n");
      out.write("\t\t\t\t$('#bpId').val(currentRowData.id);\r\n");
      out.write("\t\t\t\t$('#bpName').val(currentRowData.partnerName);\r\n");
      out.write("\t\t\t\t$('#bpTelNo').val(currentRowData.telno);\r\n");
      out.write("\t\t\t\t$('#bpMail').val(currentRowData.email);\r\n");
      out.write("\t\t\t\t$('#bpAddress').val(currentRowData.address);\r\n");
      out.write("\t\t\t\t$('#bpNote').val(currentRowData.note);\r\n");
      out.write("\t\t\t\t$('#businessPartnerModalLabel').text('Müşteri Ekleme - Güncelleme');\r\n");
      out.write("\t\t\t\t$('#businessPartnerModal').modal('show');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tgetBusinessPartners = function(){\r\n");
      out.write("\t\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\t\tjsonreq.params[0] = \"get_all_bp\";\r\n");
      out.write("\t\t\t\tsendAjaxBP(jsonreq,\"/Accounting/AccountingServlet\",true,\"POST\");\r\n");
      out.write("\t\t\t\tconsole.log('loaded');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdeleteBusinessPartner = function(){\r\n");
      out.write("\t\t\t\tif(confirm(currentRowData.partnerName + ' isimli müşteriyi silmek istediğinize emin misiniz?')){\r\n");
      out.write("\t\t\t\t\tvar deleteId = currentRowData.id;\r\n");
      out.write("\t\t\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\t\t\tjsonreq.params[0] = \"delete_bp\";\r\n");
      out.write("\t\t\t\t\tjsonreq.params[1] = deleteId;\r\n");
      out.write("\t\t\t\t\tsendAjaxBP(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfillBusinessPartnersTable = function(data){\r\n");
      out.write("\t\t\t\tif(typeof businessPartnerTable == 'undefined'){\r\n");
      out.write("\t\t\t\t\tbusinessPartnerTable = $('#businessPartnersTable').DataTable({\r\n");
      out.write("\t\t\t\t\t\t\"language\": {\r\n");
      out.write("\t\t\t\t            \"lengthMenu\": \"Sayfa başına _MENU_ kayıt\",\r\n");
      out.write("\t\t\t\t            \"zeroRecords\": \"Nothing found - sorry\",\r\n");
      out.write("\t\t\t\t            \"info\": \"_PAGE_ sayfadan _PAGES_ gösteriliyor\",\r\n");
      out.write("\t\t\t\t            \"infoEmpty\": \"Data bulunamadı\",\r\n");
      out.write("\t\t\t\t            \"infoFiltered\": \"(filtered from _MAX_ total records)\",\r\n");
      out.write("\t\t\t\t            \"search\" : \"Arama\",\r\n");
      out.write("\t\t\t\t            \"paginate\": {\r\n");
      out.write("\t\t\t\t                \"previous\": \"Geri\",\r\n");
      out.write("\t\t\t\t                \"next\" : \"İleri\"\r\n");
      out.write("\t\t\t\t            }\r\n");
      out.write("\t\t\t\t        },\r\n");
      out.write("\t\t\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t\t\t\t\"columns\" : [\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"id\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"partnerName\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"telno\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"email\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"address\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"note\"\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tbusinessPartnerTable.clear();\r\n");
      out.write("\t\t\t\t\tbusinessPartnerTable.rows.add(data);\r\n");
      out.write("\t\t\t\t\tbusinessPartnerTable.draw();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#businessPartnersTable tbody').on('click', 'tr', function () {\r\n");
      out.write("\t\t\t\t\tif ($(this).hasClass('selectedRow') ) {\r\n");
      out.write("\t\t\t            $(this).removeClass('selectedRow');\r\n");
      out.write("\t\t\t            $('#updateBusinessPartnerBtn').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t            $('#deleteBusinessPartnerBtn').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t        } else {\r\n");
      out.write("\t\t\t        \tbusinessPartnerTable.$('tr.selectedRow').removeClass('selectedRow');\r\n");
      out.write("\t\t\t            $(this).addClass('selectedRow');\r\n");
      out.write("\t\t\t            var data = businessPartnerTable.row(this).data();\r\n");
      out.write("\t\t\t            currentRowData = data;\r\n");
      out.write("\t\t\t            $('#updateBusinessPartnerBtn').attr(\"disabled\",false);\r\n");
      out.write("\t\t\t            $('#deleteBusinessPartnerBtn').attr(\"disabled\",false);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tgetBusinessPartners();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div class=\"card\">\r\n");
      out.write("\t\t<div class=\"card-header\">\r\n");
      out.write("    \t\tMüşteriler\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<div class=\"card-body\">\r\n");
      out.write("  \t\t\t<div style=\"padding:10px;height:100%\">\r\n");
      out.write("\t\t\t\t<table id=\"businessPartnersTable\" class=\"table table-hover\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Müşteri Adı</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Telefon No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>E-Mail</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Adress</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Müşteri Notu</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"btn-group\" role=\"group\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-success btn-sm\" id=\"newBusinessPartnerBtn\">Yeni Kayıt</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" id=\"updateBusinessPartnerBtn\" disabled>Düzenle</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-danger btn-sm\" id=\"deleteBusinessPartnerBtn\" disabled>Sil</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"businessPartnerModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"businessPartnerModalLabel\">Müşteri Ekleme</h5>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<input id=\"bpId\" type=\"hidden\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">Müşteri Adı:</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\"><input class=\"form-control\" id=\"bpName\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">Telefon No:</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\"><input class=\"form-control\" id=\"bpTelNo\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">E-mail:</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\"><input class=\"form-control\" id=\"bpMail\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">Adress:</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\"><textarea style=\"resize:none\" class=\"form-control\" id=\"bpAddress\"></textarea></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">Müşteri Notu:</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\"><textarea style=\"resize:none\" class=\"form-control\" id=\"bpNote\"></textarea></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-sm btn-success\" id=\"businessPartnerSaveBtn\">Kaydet</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- MAIN CONTENT START -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
