/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-31 12:32:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.accountingapp.model.User;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.accountingapp.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/headerandmenu.jsp", out, false);
      out.write("\r\n");
      out.write("<link href=\"../include/css/dataTables.bootstrap4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../include/select2/select2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"../include/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"../include/js/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("<script src=\"../include/select2/select2.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("var sendAjaxDB;\r\n");
      out.write("var getUserMenuTable;\r\n");
      out.write("var fillUserMenuTable;\r\n");
      out.write("var userMenuTable;\r\n");
      out.write("var userRoleTable;\r\n");
      out.write("var currentRowDataMenu;\r\n");
      out.write("var currentRowDataRoles;\r\n");
      out.write("var getUserRoles;\r\n");
      out.write("var fillUserRoleTable;\r\n");
      out.write("var getRoleNames;\r\n");
      out.write("var fillUserRoleSelect;\r\n");
      out.write("var rolesTable;\r\n");
      out.write("var fillRolesTable;\r\n");
      out.write("var currentRowDataRolesTable;\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$('#userRolesSelect').select2();\r\n");
      out.write("\tsendAjaxDB = function(jsonreq,url,async,type){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\ttype : type,\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tdata : JSON.stringify(jsonreq),\r\n");
      out.write("\t\t\tcontentType : 'application/json',\r\n");
      out.write("\t\t\tmimeType : 'application/json',\r\n");
      out.write("\t\t\tasync : async,\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\tif(typeof data == 'string' && data.includes(\"redirect_url\")){\r\n");
      out.write("\t\t\t\t\twindow.location.href = data.split(\":\")[1];\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"get_user_menus_with_roles\"){\r\n");
      out.write("\t\t\t\t\t\tfillUserMenuTable(data);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"get_role_names\"){\r\n");
      out.write("\t\t\t\t\t\tfillUserRoleSelect(data);\r\n");
      out.write("\t\t\t\t\t\tfillRolesTable(data);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"usermenu_save\"){\r\n");
      out.write("\t\t\t\t\t\tif(data != \"0\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"İşlem başarılı\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"usermenu_delete\"){\r\n");
      out.write("\t\t\t\t\t\tif(data != \"0\"){\r\n");
      out.write("\t\t\t\t\t\t\talert('İşlem başarılı');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"get_user_roles\"){\r\n");
      out.write("\t\t\t\t\t\tfillUserRoleTable(data);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"user_role_save\"){\r\n");
      out.write("\t\t\t\t\t\tif(data == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"İşlem başarılı.\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"update_user_role\"){\r\n");
      out.write("\t\t\t\t\t\tif(data == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"İşlem başarılı.\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfillRolesTable = function(data){\r\n");
      out.write("\t\tif(typeof rolesTable == 'undefined'){\r\n");
      out.write("\t\t\trolesTable = $('#rolesTable').DataTable({\r\n");
      out.write("\t\t\t\t\"language\": {\r\n");
      out.write("\t\t            \"lengthMenu\": \"Sayfa başına _MENU_ kayıt\",\r\n");
      out.write("\t\t            \"zeroRecords\": \"Nothing found - sorry\",\r\n");
      out.write("\t\t            \"info\": \"_PAGE_ sayfadan _PAGES_ gösteriliyor\",\r\n");
      out.write("\t\t            \"infoEmpty\": \"Data bulunamadı\",\r\n");
      out.write("\t\t            \"infoFiltered\": \"(filtered from _MAX_ total records)\",\r\n");
      out.write("\t\t            \"search\" : \"Arama\",\r\n");
      out.write("\t\t            \"paginate\": {\r\n");
      out.write("\t\t                \"previous\": \"Geri\",\r\n");
      out.write("\t\t                \"next\" : \"İleri\"\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t\t\"columns\" : [\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"id\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"roleName\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"roleCode\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\trolesTable.clear();\r\n");
      out.write("\t\t\trolesTable.rows.add(data);\r\n");
      out.write("\t\t\trolesTable.draw();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#rolesTable tbody').on('click', 'tr', function () {\r\n");
      out.write("\t\t\tif ($(this).hasClass('selectedRow') ) {\r\n");
      out.write("\t            $(this).removeClass('selectedRow');\r\n");
      out.write("\t            $('#updateRoleButton').attr(\"disabled\",true);\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t        \trolesTable.$('tr.selectedRow').removeClass('selectedRow');\r\n");
      out.write("\t            $(this).addClass('selectedRow');\r\n");
      out.write("\t            var data = rolesTable.row(this).data();\r\n");
      out.write("\t            currentRowDataRolesTable = data;\r\n");
      out.write("\t            $('#updateRoleButton').attr(\"disabled\",false);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("\tgetUserRoles = function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"get_user_roles\"\r\n");
      out.write("\t\tsendAjaxDB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$('#userMenuRoleUpdateBtn').on('click',function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"update_user_role\";\r\n");
      out.write("\t\tjsonreq.params[1] = $('#userRoleIdInput').val();\r\n");
      out.write("\t\tjsonreq.params[2] = $('#userRolesMenuSelect').val();\r\n");
      out.write("\t\tsendAjaxDB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#updateRoleButton').on('click',function(){\r\n");
      out.write("\t\t$('#roleIdInput').val(currentRowDataRolesTable.id);\r\n");
      out.write("\t\t$('#roleNameInput').val(currentRowDataRolesTable.roleName);\r\n");
      out.write("\t\t$('#roleCodeInput').val(currentRowDataRolesTable.roleCode);\r\n");
      out.write("\t\t$('#rolesModal').modal('show');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfillUserRoleTable = function(data){\r\n");
      out.write("\t\tif(typeof userRoleTable == 'undefined'){\r\n");
      out.write("\t\t\tuserRoleTable = $('#rolesMenuTable').DataTable({\r\n");
      out.write("\t\t\t\t\"language\": {\r\n");
      out.write("\t\t            \"lengthMenu\": \"Sayfa başına _MENU_ kayıt\",\r\n");
      out.write("\t\t            \"zeroRecords\": \"Nothing found - sorry\",\r\n");
      out.write("\t\t            \"info\": \"_PAGE_ sayfadan _PAGES_ gösteriliyor\",\r\n");
      out.write("\t\t            \"infoEmpty\": \"Data bulunamadı\",\r\n");
      out.write("\t\t            \"infoFiltered\": \"(filtered from _MAX_ total records)\",\r\n");
      out.write("\t\t            \"search\" : \"Arama\",\r\n");
      out.write("\t\t            \"paginate\": {\r\n");
      out.write("\t\t                \"previous\": \"Geri\",\r\n");
      out.write("\t\t                \"next\" : \"İleri\"\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t\t\"columns\" : [\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"id\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"userMail\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"roleName\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tuserRoleTable.clear();\r\n");
      out.write("\t\t\tuserRoleTable.rows.add(data);\r\n");
      out.write("\t\t\tuserRoleTable.draw();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#rolesMenuTable tbody').on('click', 'tr', function () {\r\n");
      out.write("\t\t\tif ($(this).hasClass('selectedRow') ) {\r\n");
      out.write("\t            $(this).removeClass('selectedRow');\r\n");
      out.write("\t            $('#updateUserRoleButton').attr(\"disabled\",true);\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t        \tuserRoleTable.$('tr.selectedRow').removeClass('selectedRow');\r\n");
      out.write("\t            $(this).addClass('selectedRow');\r\n");
      out.write("\t            var data = userRoleTable.row(this).data();\r\n");
      out.write("\t            currentRowDataRoles = data;\r\n");
      out.write("\t            $('#userRoleIdInput').val(currentRowDataRoles.id);\r\n");
      out.write("\t            $('#userRoleUsernameLabel').text(currentRowDataRoles.userMail);\r\n");
      out.write("\t            $('#userRolesMenuSelect').val(currentRowDataRoles.userRole);\r\n");
      out.write("\t            $('#updateUserRoleButton').attr(\"disabled\",false);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfillUserRoleSelect = function(data){\r\n");
      out.write("\t\tfor(var i = 0 ; i < data.length ; i++){\r\n");
      out.write("\t\t\tvar selectOption = \"<option value='\"+data[i].roleCode+\"'>\"+data[i].roleName+\"</option>\";\r\n");
      out.write("\t\t\t$('#userRolesSelect').append(selectOption);\r\n");
      out.write("\t\t\t$('#userRolesMenuSelect').append(selectOption);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tgetUserMenuTable = function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"get_user_menus_with_roles\"\r\n");
      out.write("\t\tsendAjaxDB(jsonreq,\"/Accounting/AccountingServlet\",true,\"POST\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tgetRoleNames = function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"get_role_names\";\r\n");
      out.write("\t\tsendAjaxDB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfillUserMenuTable = function(data){\r\n");
      out.write("\t\tif(typeof userMenuTable == 'undefined'){\r\n");
      out.write("\t\t\tuserMenuTable = $('#userMenuTable').DataTable({\r\n");
      out.write("\t\t\t\t\"language\": {\r\n");
      out.write("\t\t            \"lengthMenu\": \"Sayfa başına _MENU_ kayıt\",\r\n");
      out.write("\t\t            \"zeroRecords\": \"Nothing found - sorry\",\r\n");
      out.write("\t\t            \"info\": \"_PAGE_ sayfadan _PAGES_ gösteriliyor\",\r\n");
      out.write("\t\t            \"infoEmpty\": \"Data bulunamadı\",\r\n");
      out.write("\t\t            \"infoFiltered\": \"(filtered from _MAX_ total records)\",\r\n");
      out.write("\t\t            \"search\" : \"Arama\",\r\n");
      out.write("\t\t            \"paginate\": {\r\n");
      out.write("\t\t                \"previous\": \"Geri\",\r\n");
      out.write("\t\t                \"next\" : \"İleri\"\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t\t\"columns\" : [\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"id\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"menuLabel\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"menuSrc\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tuserMenuTable.clear();\r\n");
      out.write("\t\t\tuserMenuTable.rows.add(data);\r\n");
      out.write("\t\t\tuserMenuTable.draw();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#userMenuTable tbody').on('click', 'tr', function () {\r\n");
      out.write("\t\t\tif ($(this).hasClass('selectedRow') ) {\r\n");
      out.write("\t            $(this).removeClass('selectedRow');\r\n");
      out.write("\t            $('#updateMenuBtn').attr(\"disabled\",true);\r\n");
      out.write("\t            $('#deleteMenuBtn').attr(\"disabled\",true);\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t        \tuserMenuTable.$('tr.selectedRow').removeClass('selectedRow');\r\n");
      out.write("\t            $(this).addClass('selectedRow');\r\n");
      out.write("\t            var data = userMenuTable.row(this).data();\r\n");
      out.write("\t            currentRowDataMenu = data;\r\n");
      out.write("\t            $('#updateMenuBtn').attr(\"disabled\",false);\r\n");
      out.write("\t            $('#deleteMenuBtn').attr(\"disabled\",false);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$('#userMenuSaveButton').on('click',function(){\r\n");
      out.write("\t\tvar menuObj = new Object();\r\n");
      out.write("\t\tmenuObj.roles = new Array();\r\n");
      out.write("\t\tif($('#userMenuIdInput').val().length > 0){\r\n");
      out.write("\t\t\tmenuObj.id = $('#userMenuIdInput').val();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tmenuObj.menuLabel = $('#menuLabelInput').val();\r\n");
      out.write("\t\tmenuObj.menuSrc = $('#menuSrcInput').val();\r\n");
      out.write("\t\tmenuObj.roles = $('#userRolesSelect').val();\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"usermenu_save\";\r\n");
      out.write("\t\tjsonreq.params[1] = JSON.stringify(menuObj);\r\n");
      out.write("\t\tsendAjaxDB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#newMenuBtn').on('click',function(){\r\n");
      out.write("\t\t$('#userMenuIdInput').val('');\r\n");
      out.write("\t\t$('#menuLabelInput').val('');\r\n");
      out.write("\t\t$('#menuSrcInput').val('');\r\n");
      out.write("\t\t$('#userRolesSelect').val('').trigger('change');\r\n");
      out.write("\t\t$('#userMenuModal').modal('show');\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#updateMenuBtn').on('click',function(){\r\n");
      out.write("\t\t$('#userMenuIdInput').val(currentRowDataMenu.id);\r\n");
      out.write("\t\t$('#menuLabelInput').val(currentRowDataMenu.menuLabel);\r\n");
      out.write("\t\t$('#menuSrcInput').val(currentRowDataMenu.menuSrc);\r\n");
      out.write("\t\t$('#userRolesSelect').val(currentRowDataMenu.roles).trigger('change');\r\n");
      out.write("\t\t$('#userMenuModal').modal('show');\r\n");
      out.write("\t\tconsole.log(currentRowDataMenu)\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#deleteMenuBtn').on('click',function(){\r\n");
      out.write("\t\tif(confirm(currentRowDataMenu.menuLabel + \" silinecek. Emin misiniz?\")){\r\n");
      out.write("\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\tjsonreq.params[0] = \"usermenu_delete\";\r\n");
      out.write("\t\t\tjsonreq.params[1] = currentRowDataMenu.id\r\n");
      out.write("\t\t\tsendAjaxDB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#updateUserRoleButton').on('click',function(){\r\n");
      out.write("\t\t$('#userRoleIdInput').val(currentRowDataRoles.id);\r\n");
      out.write("\t\t$('#userRoleModal').modal('show');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#userMenuRoleSaveBtn').on('click',function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"user_role_save\";\r\n");
      out.write("\t\tvar roleObj = new Object();\r\n");
      out.write("\t\tif($('#roleIdInput').val().length > 0){\r\n");
      out.write("\t\t\troleObj.id = $('#roleIdInput').val();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\troleObj.roleName = $('#roleNameInput').val();\r\n");
      out.write("\t\troleObj.roleCode = $('#roleCodeInput').val();\r\n");
      out.write("\t\tjsonreq.params[1] = JSON.stringify(roleObj);\r\n");
      out.write("\t\tsendAjaxDB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#insertNewRoleButton').on('click',function(){\r\n");
      out.write("\t\t$('#rolesModal').modal('show');\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\tgetUserMenuTable();\r\n");
      out.write("\tgetRoleNames();\r\n");
      out.write("\tgetUserRoles();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<!-- MAIN CONTENT START -->\r\n");
      out.write("<br>\r\n");
      out.write("<div style=\"margin-left: 10px\">\r\n");
      out.write("\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t<li class=\"nav-item waves-effect waves-light\">\r\n");
      out.write("\t\t\t<a class=\"nav-link active\"  data-toggle=\"tab\" href=\"#menuOperationsTab\" role=\"tab\" aria-selected=\"true\">Menü İşlemleri</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"nav-item waves-effect waves-light\">\r\n");
      out.write("\t\t\t<a class=\"nav-link\" data-toggle=\"tab\" href=\"#rolesMenuTab\" role=\"tab\" aria-selected=\"false\">Yetki İşlemleri</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"tab-content\" id=\"menuOperationsTabContent\">\r\n");
      out.write("    \t<div class=\"tab-pane fade active show\" id=\"menuOperationsTab\" role=\"tabpanel\" >\r\n");
      out.write("    \t\t<br>\r\n");
      out.write("\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("    \t\t\t\tMenüler\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<table id=\"userMenuTable\" class=\"table table-hover\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Menü Adı</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Menü Adresi</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group\" role=\"group\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-success btn-sm\" id=\"newMenuBtn\">Yeni Kayıt</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" id=\"updateMenuBtn\" disabled>Düzenle</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-danger btn-sm\" id=\"deleteMenuBtn\" disabled>Sil</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<div class=\"tab-pane fade\" id=\"rolesMenuTab\" role=\"tabpanel\" >\r\n");
      out.write("    \t\t<br>\r\n");
      out.write("    \t\t<div class=\"row\">\r\n");
      out.write("    \t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("    \t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("    \t\t\t\t\t\tYetkiler\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<table id=\"rolesMenuTable\" class=\"table table-hover\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Kullanıcı Adı</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Kullanıcı Rolü</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"btn-group\" role=\"group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" id=\"updateUserRoleButton\" disabled>Düzenle</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("    \t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("    \t\t\t\t\t\tRoller\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<table id=\"rolesTable\" class=\"table table-hover\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Rol Adı</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Rol Kodu</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"btn-group\" role=\"group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-success btn-sm\" id=\"insertNewRoleButton\">Yeni Rol Tanımla</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" id=\"updateRoleButton\" disabled>Düzenle</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"modal fade\" id=\"userMenuModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"userMenuModalLabel\">Müşteri Ekleme</h5>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"userMenuIdInput\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">Menü Adı</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\"><input class=\"form-controller\" id=\"menuLabelInput\" style=\"width:100%\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">Menü Adresi</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\"><input class=\"form-controller\" id=\"menuSrcInput\" style=\"width:100%\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">Yetkisi Olanlar</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<select class=\"js-example-basic-multiple\" id=\"userRolesSelect\" multiple=\"multiple\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-sm btn-success\" id=\"userMenuSaveButton\">Kaydet</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"userRoleModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-md\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"userRoleUsernameLabel\">Rol Güncelleme</h5>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"userRoleIdInput\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<select style=\"width:100%\" id=\"userRolesMenuSelect\" class=\"form-controller form-select form-select-lg mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-sm btn-success\" id=\"userMenuRoleUpdateBtn\">Kaydet</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"rolesModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-md\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"userRoleUsernameLabel\">Rol Tanımlama</h5>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"roleIdInput\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">Rol Adı:</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\"><input id=\"roleNameInput\" class=\"form-control\"/></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">Rol Kodu:</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\"><input type=\"number\" id=\"roleCodeInput\" class=\"form-control\"/></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-sm btn-success\" id=\"userMenuRoleSaveBtn\">Kaydet</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- MAIN CONTENT START -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
