/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-27 19:21:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.accountingapp.model.User;

public final class sellandbuy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.accountingapp.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/headerandmenu.jsp", out, false);
      out.write("\r\n");
      out.write("<link href=\"../include/css/dataTables.bootstrap4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../include/select2/select2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"../include/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"../include/js/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("<script src=\"../include/select2/select2.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("var sendAjaxSB;\r\n");
      out.write("var getBusinessPartners;\r\n");
      out.write("var getInventoryItems;\r\n");
      out.write("var fillInventoryItems;\r\n");
      out.write("var fillBusinessPartners;\r\n");
      out.write("var currentItemInfos;\r\n");
      out.write("var getItemPrice;\r\n");
      out.write("var fillCashBoxSelect;\r\n");
      out.write("var getCashBoxes;\r\n");
      out.write("var getLastSell;\r\n");
      out.write("var getSell;\r\n");
      out.write("var getBuy;\r\n");
      out.write("var getLastBuy;\r\n");
      out.write("var fillBuyingOperationsTable;\r\n");
      out.write("var fillSellingOperationsTable;\r\n");
      out.write("var buyingTable;\r\n");
      out.write("var sellingTable;\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$('#businessPartnersSelect').select2();\r\n");
      out.write("\t$('#inventorySelect').select2();\r\n");
      out.write("\t$('#operationCashBox').select2();\r\n");
      out.write("\tsendAjaxSB = function(jsonreq,url,async,type){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\ttype : type,\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tdata : JSON.stringify(jsonreq),\r\n");
      out.write("\t\t\tcontentType : 'application/json',\r\n");
      out.write("\t\t\tmimeType : 'application/json',\r\n");
      out.write("\t\t\tasync : async,\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\tif(typeof data == \"string\" && data.includes(\"redirect_url\")){\r\n");
      out.write("\t\t\t\t\twindow.location.href = data.split(\":\")[1];\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"get_all_bp\"){\r\n");
      out.write("\t\t\t\t\t\tfillBusinessPartners(data);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"get_inventory_items\"){\r\n");
      out.write("\t\t\t\t\t\tcurrentItemInfos = data;\r\n");
      out.write("\t\t\t\t\t\tfillInventoryItems(data);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"get_cash_boxes\"){\r\n");
      out.write("\t\t\t\t\t\tfillCashBoxSelect(data);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"save_selling_operation\"){\r\n");
      out.write("\t\t\t\t\t\tif(data == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\talert('İşlem başarılı');\r\n");
      out.write("\t\t\t\t\t\t} else if(data == \"2\"){\r\n");
      out.write("\t\t\t\t\t\t\talert('Miktarı karşılayacak yeterli stok bulunmamaktadır.');\r\n");
      out.write("\t\t\t\t\t\t} else if(data == \"3\"){\r\n");
      out.write("\t\t\t\t\t\t\talert('İşlem başarısız');\r\n");
      out.write("\t\t\t\t\t\t} else if(data == \"4\"){\r\n");
      out.write("\t\t\t\t\t\t\talert('İşlem başarısız');\r\n");
      out.write("\t\t\t\t\t\t} else if(data == \"5\"){\r\n");
      out.write("\t\t\t\t\t\t\talert('İşlem başarısız');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"save_buying_operation\"){\r\n");
      out.write("\t\t\t\t\t\tif(data == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\talert('İşlem başarılı');\r\n");
      out.write("\t\t\t\t\t\t} else if(data == \"2\"){\r\n");
      out.write("\t\t\t\t\t\t\talert('İşlem başarılı');\r\n");
      out.write("\t\t\t\t\t\t} else if(data == \"3\"){\r\n");
      out.write("\t\t\t\t\t\t\talert('İşlemi gerçekleştirmek için kasanızda yeterli hacim bulunmamaktadır.');\r\n");
      out.write("\t\t\t\t\t\t} else if(data == \"4\"){\r\n");
      out.write("\t\t\t\t\t\t\talert('İşlem başarısız');\r\n");
      out.write("\t\t\t\t\t\t} else if(data == \"5\"){\r\n");
      out.write("\t\t\t\t\t\t\talert('İşlem başarısız');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"get_last_operation\"){\r\n");
      out.write("\t\t\t\t\t\tif(jsonreq.params[1] == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\t$('#sellLabelBp').text(data.bpName);\r\n");
      out.write("\t\t\t\t\t\t\t$('#sellLabelItem').text(data.itemName);\r\n");
      out.write("\t\t\t\t\t\t\t$('#sellLabelQty').text(data.itemQty);\r\n");
      out.write("\t\t\t\t\t\t\t$('#sellLabelBalance').text(data.totalPrice);\r\n");
      out.write("\t\t\t\t\t\t\t$('#sellLabelTime').text(data.operationTime);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(jsonreq.params[1] == \"0\"){\r\n");
      out.write("\t\t\t\t\t\t\t$('#buyLabelBp').text(data.bpName);\r\n");
      out.write("\t\t\t\t\t\t\t$('#buyLabelItem').text(data.itemName);\r\n");
      out.write("\t\t\t\t\t\t\t$('#buyLabelQty').text(data.itemQty);\r\n");
      out.write("\t\t\t\t\t\t\t$('#buyLabelBalance').text(data.totalPrice);\r\n");
      out.write("\t\t\t\t\t\t\t$('#buyLabelTime').text(data.operationTime);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(jsonreq.params[0] == \"get_operations\"){\r\n");
      out.write("\t\t\t\t\t\tif(jsonreq.params[1] == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\tfillBuyingOperationsTable(data);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(jsonreq.params[1] == \"0\"){\r\n");
      out.write("\t\t\t\t\t\t\tfillSellingOperationsTable(data);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},error : function(e){\r\n");
      out.write("\t\t\t\tconsole.log(e);\r\n");
      out.write("            \talert('ERROR '+e.responseText)\r\n");
      out.write("            }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfillBuyingOperationsTable = function(data){\r\n");
      out.write("\t\tif(typeof buyingTable == 'undefined'){\r\n");
      out.write("\t\t\tbuyingTable = $('#buyingTable').DataTable({\r\n");
      out.write("\t\t\t\t\"language\": {\r\n");
      out.write("\t\t            \"lengthMenu\": \"Sayfa başına _MENU_ kayıt\",\r\n");
      out.write("\t\t            \"zeroRecords\": \"Nothing found - sorry\",\r\n");
      out.write("\t\t            \"info\": \"_PAGE_ sayfadan _PAGES_ gösteriliyor\",\r\n");
      out.write("\t\t            \"infoEmpty\": \"Data bulunamadı\",\r\n");
      out.write("\t\t            \"infoFiltered\": \"(filtered from _MAX_ total records)\",\r\n");
      out.write("\t\t            \"search\" : \"Arama\",\r\n");
      out.write("\t\t            \"paginate\": {\r\n");
      out.write("\t\t                \"previous\": \"Geri\",\r\n");
      out.write("\t\t                \"next\" : \"İleri\"\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t\t\"columns\" : [\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"id\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"bpName\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: null,\r\n");
      out.write("\t\t\t\t\t\t\"render\" : function(data,type,full,meta) {\r\n");
      out.write("\t\t\t\t\t\t\tif(data.operationType == \"0\"){\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"Satış\"\r\n");
      out.write("\t\t\t\t\t\t\t} else if(data.operationType == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"Alış\";\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"itemName\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"itemQty\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"totalPrice\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"operationTime\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tbuyingTable.clear();\r\n");
      out.write("\t\t\tbuyingTable.rows.add(data);\r\n");
      out.write("\t\t\tbuyingTable.draw();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfillSellingOperationsTable = function(data){\r\n");
      out.write("\t\tif(typeof sellingTable == 'undefined'){\r\n");
      out.write("\t\t\tsellingTable = $('#sellingTable').DataTable({\r\n");
      out.write("\t\t\t\t\"language\": {\r\n");
      out.write("\t\t            \"lengthMenu\": \"Sayfa başına _MENU_ kayıt\",\r\n");
      out.write("\t\t            \"zeroRecords\": \"Nothing found - sorry\",\r\n");
      out.write("\t\t            \"info\": \"_PAGE_ sayfadan _PAGES_ gösteriliyor\",\r\n");
      out.write("\t\t            \"infoEmpty\": \"Data bulunamadı\",\r\n");
      out.write("\t\t            \"infoFiltered\": \"(filtered from _MAX_ total records)\",\r\n");
      out.write("\t\t            \"search\" : \"Arama\",\r\n");
      out.write("\t\t            \"paginate\": {\r\n");
      out.write("\t\t                \"previous\": \"Geri\",\r\n");
      out.write("\t\t                \"next\" : \"İleri\"\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t\t\"columns\" : [\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"id\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"bpName\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: null,\r\n");
      out.write("\t\t\t\t\t\t\"render\" : function(data,type,full,meta) {\r\n");
      out.write("\t\t\t\t\t\t\tif(data.operationType == \"0\"){\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"Satış\"\r\n");
      out.write("\t\t\t\t\t\t\t} else if(data.operationType == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"Alış\";\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"itemName\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"itemQty\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"totalPrice\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdata: \"operationTime\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tsellingTable.clear();\r\n");
      out.write("\t\t\tsellingTable.rows.add(data);\r\n");
      out.write("\t\t\tsellingTable.draw();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tgetSell = function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"get_operations\";\r\n");
      out.write("\t\tjsonreq.params[1] = \"0\"\r\n");
      out.write("\t\tsendAjaxSB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tgetBuy = function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"get_operations\";\r\n");
      out.write("\t\tjsonreq.params[1] = \"1\"\r\n");
      out.write("\t\tsendAjaxSB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tgetLastSell = function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"get_last_operation\";\r\n");
      out.write("\t\tjsonreq.params[1] = \"0\"\r\n");
      out.write("\t\tsendAjaxSB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tgetLastBuy = function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"get_last_operation\";\r\n");
      out.write("\t\tjsonreq.params[1] = \"1\"\r\n");
      out.write("\t\tsendAjaxSB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfillCashBoxSelect = function(data){\r\n");
      out.write("\t\t$('[name=operationCashBoxnm]').empty();\r\n");
      out.write("\t\tfor(var i = 0 ; i < data.length ; i++){\r\n");
      out.write("\t\t\tvar option = \"<option value=\"+data[i].id+\">\"+data[i].cashBoxName + \" - \" + data[i].cashBoxBalance +\"</option>\";\r\n");
      out.write("\t\t\t$('[name=operationCashBoxnm]').append(option);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$('[name=operationCashBoxnm]').prop(\"selectedIndex\", 0).trigger('change');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tgetCashBoxes = function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"get_cash_boxes\";\r\n");
      out.write("\t\tsendAjaxSB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tgetItemPrice = function(itemId){\r\n");
      out.write("\t\tfor(var i = 0 ; i < currentItemInfos.length ; i++){\r\n");
      out.write("\t\t\tif(currentItemInfos[i].itemId == itemId){\r\n");
      out.write("\t\t\t\treturn currentItemInfos[i].itemPrice;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfillBusinessPartners = function(data){\r\n");
      out.write("\t\t$('[name=businessPartnersSelectnm]').empty();\r\n");
      out.write("\t\tfor(var i = 0 ; i < data.length ; i++){\r\n");
      out.write("\t\t\tvar options = \"<option value='\"+data[i].id+\"'>\"+data[i].partnerName+\"</option>\";\r\n");
      out.write("\t\t\t$('[name=businessPartnersSelectnm]').append(options);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$('[name=businessPartnersSelectnm]').prop(\"selectedIndex\", 0).trigger('change');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfillInventoryItems = function(data){\r\n");
      out.write("\t\t$('[name=inventorySelectnm]').empty();\r\n");
      out.write("\t\tfor(var i = 0 ; i < data.length ; i++){\r\n");
      out.write("\t\t\tvar options = \"<option value='\"+data[i].itemId+\"'>\"+data[i].itemName+\"</option>\";\r\n");
      out.write("\t\t\t$('[name=inventorySelectnm]').append(options);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$('[name=inventorySelectnm]').prop(\"selectedIndex\", 0).trigger('change');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tgetInventoryItems = function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"get_inventory_items\";\r\n");
      out.write("\t\tsendAjaxSB(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tgetBusinessPartners = function(){\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"get_all_bp\";\r\n");
      out.write("\t\tsendAjaxSB(jsonreq,\"/Accounting/AccountingServlet\",true,\"POST\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$('#itemQtyInput').on('keyup',function(){\r\n");
      out.write("\t\tvar totalInput = $('#itemQtyInput').val() * getItemPrice($('#inventorySelect').val());\r\n");
      out.write("\t\t$('#totalPriceInput').val(totalInput);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#itemQtyInputBuy').on('keyup',function(){\r\n");
      out.write("\t\tvar totalInput = $('#itemQtyInputBuy').val() * $('#unitPriceInputBuy').val();\r\n");
      out.write("\t\t$('#totalPriceInputBuy').val(totalInput);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#inventorySelect').on('change',function(){\r\n");
      out.write("\t\t$('#unitPriceInput').val(getItemPrice($('#inventorySelect').val()));\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#newSellButton').on('click',function(){\r\n");
      out.write("\t\t$('#sellModal').modal('show');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#newBuyButton').on('click',function(){\r\n");
      out.write("\t\t$('#buyModal').modal('show');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#sellItemButton').on('click',function(){\r\n");
      out.write("\t\tvar sellingObj = new Object();\r\n");
      out.write("\t\tsellingObj.businessPartner = $('[name=businessPartnersSelectnm]').val();\r\n");
      out.write("\t\tsellingObj.item = $('[name=inventorySelectnm]').val();\r\n");
      out.write("\t\tsellingObj.itemQty = $('#itemQtyInput').val();\r\n");
      out.write("\t\tsellingObj.cashBox = $('[name=operationCashBoxnm]').val();\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"save_selling_operation\";\r\n");
      out.write("\t\tjsonreq.params[1] = JSON.stringify(sellingObj);\r\n");
      out.write("\t\tsendAjaxSB(jsonreq,\"/Accounting/AccountingServlet\",true,\"POST\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#buyItemButton').on('click',function(){\r\n");
      out.write("\t\tvar sellingObj = new Object();\r\n");
      out.write("\t\tsellingObj.businessPartner = $('[name=businessPartnersSelectnm]').val();\r\n");
      out.write("\t\tsellingObj.item = $('[name=inventorySelectnm]').val();\r\n");
      out.write("\t\tsellingObj.itemQty = $('#itemQtyInputBuy').val();\r\n");
      out.write("\t\tsellingObj.cashBox = $('[name=operationCashBoxnm]').val();\r\n");
      out.write("\t\tsellingObj.itemPrice = $('#unitPriceInputBuy').val();\r\n");
      out.write("\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\tjsonreq.params[0] = \"save_buying_operation\";\r\n");
      out.write("\t\tjsonreq.params[1] = JSON.stringify(sellingObj);\r\n");
      out.write("\t\tsendAjaxSB(jsonreq,\"/Accounting/AccountingServlet\",true,\"POST\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tgetBusinessPartners();\r\n");
      out.write("\tgetInventoryItems();\r\n");
      out.write("\tgetCashBoxes();\r\n");
      out.write("\tgetLastSell();\r\n");
      out.write("\tgetLastBuy();\r\n");
      out.write("\tgetSell();\r\n");
      out.write("\tgetBuy();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<!-- MAIN CONTENT START -->\r\n");
      out.write("\t<div style=\"margin-left:10px\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t<li class=\"nav-item waves-effect waves-light\">\r\n");
      out.write("\t\t\t\t<a class=\"nav-link active\"  data-toggle=\"tab\" href=\"#buyingOperationsTab\" role=\"tab\" aria-selected=\"true\">Alış İşlemleri</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item waves-effect waves-light\">\r\n");
      out.write("\t\t\t\t<a class=\"nav-link\" data-toggle=\"tab\" href=\"#sellingOperationstab\" role=\"tab\" aria-selected=\"false\">Satış İşlemleri</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("    \t<div class=\"tab-content\">\r\n");
      out.write("    \t\t<div class=\"tab-pane fade active show\" id=\"buyingOperationsTab\" role=\"tabpanel\" >\r\n");
      out.write("    \t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("    \t\t\t\t\tSatın Alma Geçmişi\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"buyingTable\" class=\"table table-hover\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Müşteri Adı</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Yapılan İşlem</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Ürün Adı</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Ürün Adedi</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Toplam Tutar</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Tarih</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"tab-pane fade\" id=\"sellingOperationstab\" role=\"tabpanel\" >\r\n");
      out.write("    \t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("    \t\t\t\t\tSatış Geçmişi\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"sellingTable\" class=\"table table-hover\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Müşteri Adı</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Yapılan İşlem</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Ürün Adı</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Ürün Adedi</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Toplam Tutar</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Tarih</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    \t<br>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\tİşlemler\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<div align=\"center\" style=\"text-align:center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group\" role=\"group\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-success \" id=\"newSellButton\">Satış Gir</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-warning \" id=\"newBuyButton\"><font color=\"white\">Alış Gir</font></button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<h6>Son Satış</h6>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<b>Kime: </b> <label id=\"buyLabelBp\"></label>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<b>Ürün: </b><label id=\"buyLabelItem\"></label>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<b>Miktar: </b><label id=\"buyLabelQty\"></label>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<b>Tutar: </b><label id=\"buyLabelBalance\"></label>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<b>Tarih: </b><label id=\"buyLabelTime\"></label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\" style=\"text-align:right;\">\r\n");
      out.write("\t\t\t\t\t\t<h6>Son Alış</h6>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<b>Kimden: </b> <label id=\"sellLabelBp\"></label>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<b>Ürün: </b><label id=\"sellLabelItem\"></label>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<b>Miktar: </b><label id=\"sellLabelQty\"></label>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<b>Tutar: </b><label id=\"sellLabelBalance\"></label>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<b>Tarih: </b><label id=\"sellLabelTime\"></label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"sellModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"modal-title\">Satış Ekranı</h5>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">Müşteri:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"businessPartnersSelectnm\" id=\"businessPartnersSelect\" style=\"width:100%\" class=\"form-select\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">Ürün:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"inventorySelectnm\" id=\"inventorySelect\" style=\"width:100%\" class=\"form-select\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\tBirim Fiyat: \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"unitPriceInput\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">Miktar:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-controller\" id=\"itemQtyInput\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\tToplam Fiyat: \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"totalPriceInput\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">İşlem Yapılacak Kasa:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"operationCashBoxnm\" id=\"operationCashBox\" style=\"width:100%\" class=\"form-select\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-sm btn-success\" id=\"sellItemButton\">Satış Yap</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"buyModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"modal-title\">Alış Ekranı</h5>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">Müşteri:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"businessPartnersSelectnm\" id=\"businessPartnersSelectBuy\" style=\"width:100%\" class=\"form-select\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">Ürün:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"inventorySelectnm\" id=\"inventorySelectBuy\" style=\"width:100%\" class=\"form-select\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\tAlış Birim Fiyat: \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"unitPriceInputBuy\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">Miktar:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-controller\" id=\"itemQtyInputBuy\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\tToplam Fiyat: \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-control\" id=\"totalPriceInputBuy\" disabled>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">İşlem Yapılacak Kasa:</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"operationCashBoxnm\" id=\"operationCashBoxBuy\" style=\"width:100%\" class=\"form-select\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-sm btn-warning\" id=\"buyItemButton\"><font color=\"white\">Alış Yap</font></button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- MAIN CONTENT START -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
