/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-31 11:04:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.accountingapp.model.User;

public final class stockmovements_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.accountingapp.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/headerandmenu.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<!-- MAIN CONTENT START -->\r\n");
      out.write("<link href=\"../include/css/dataTables.bootstrap4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../include/select2/select2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"../include/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"../include/js/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("<script src=\"../include/select2/select2.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t\tvar sendAjaxSI;\r\n");
      out.write("\t\tvar getInventoryGroups;\r\n");
      out.write("\t\tvar getInventoryItems;\r\n");
      out.write("\t\tvar fillInventoryGroupTable;\r\n");
      out.write("\t\tvar fillInventoryItemTable;\r\n");
      out.write("\t\tvar inventoryGroupTable;\r\n");
      out.write("\t\tvar openUpdateModal;\r\n");
      out.write("\t\tvar currentRowDataInventoryGroup;\r\n");
      out.write("\t\tvar deleteBusinessPartner;\r\n");
      out.write("\t\tvar inventoryItemTable;\r\n");
      out.write("\t\tvar currentRowDataInventoryItem;\r\n");
      out.write("\t\tvar fillInventoryItemSelect;\r\n");
      out.write("\t\tvar getStockMovements;\r\n");
      out.write("\t\tvar stockMovementsTable;\r\n");
      out.write("\t\tvar fillStockMovementsTable;\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t$('#inventoryItemGroupCodeSelect').select2();\r\n");
      out.write("\t\t\tsendAjaxSI = function(jsonreq,url,async,type){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\ttype : type,\r\n");
      out.write("\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\tdata : JSON.stringify(jsonreq),\r\n");
      out.write("\t\t\t\t\tcontentType : 'application/json',\r\n");
      out.write("\t\t\t\t\tmimeType : 'application/json',\r\n");
      out.write("\t\t\t\t\tasync : async,\r\n");
      out.write("\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\tif(typeof data == \"string\" && data.includes(\"redirect_url\")){\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href = data.split(\":\")[1];\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tif(jsonreq.params[0] == \"get_inventory_groups\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tfillInventoryGroupTable(data);\r\n");
      out.write("\t\t\t\t\t\t\t\tfillInventoryItemSelect(data);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(jsonreq.params[0] == \"delete_inventory_group\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"Silme işlemi başarılı!\")\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(jsonreq.params[0] == \"save_inventory_group\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert('İşlem başarılı!')\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(jsonreq.params[0] == \"get_inventory_items\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tfillInventoryItemTable(data);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(jsonreq.params[0] == \"delete_inventory_item\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"Silme işlemi başarılı!\")\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(jsonreq.params[0] == \"save_inventory_item\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert('İşlem başarılı!')\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(jsonreq.params[0] == \"get_stock_movements\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tfillStockMovementsTable(data);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},error : function(e){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e);\r\n");
      out.write("\t\t            \talert('ERROR '+e.responseText)\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfillStockMovementsTable = function(data){\r\n");
      out.write("\t\t\t\tif(typeof stockMovementsTable == 'undefined'){\r\n");
      out.write("\t\t\t\t\tstockMovementsTable = $('#stockMovementsTable').DataTable({\r\n");
      out.write("\t\t\t\t\t\t\"language\": {\r\n");
      out.write("\t\t\t\t            \"lengthMenu\": \"Sayfa başına _MENU_ kayıt\",\r\n");
      out.write("\t\t\t\t            \"zeroRecords\": \"Nothing found - sorry\",\r\n");
      out.write("\t\t\t\t            \"info\": \"_PAGE_ sayfadan _PAGES_ gösteriliyor\",\r\n");
      out.write("\t\t\t\t            \"infoEmpty\": \"Data bulunamadı\",\r\n");
      out.write("\t\t\t\t            \"infoFiltered\": \"(filtered from _MAX_ total records)\",\r\n");
      out.write("\t\t\t\t            \"search\" : \"Arama\",\r\n");
      out.write("\t\t\t\t            \"paginate\": {\r\n");
      out.write("\t\t\t\t                \"previous\": \"Geri\",\r\n");
      out.write("\t\t\t\t                \"next\" : \"İleri\"\r\n");
      out.write("\t\t\t\t            }\r\n");
      out.write("\t\t\t\t        },\r\n");
      out.write("\t\t\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t\t\t\t\"columns\" : [\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"id\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"bpName\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"itemGroupCode\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"itemGroupName\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"itemCode\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"itemName\"\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t,\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"itemQty\"\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t,\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: null,\r\n");
      out.write("\t\t\t\t\t\t\t\t\"render\" : function(data,type,full,meta) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(data.operationType == \"0\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn \"<font color='red'>Çıktı</font>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else if(data.operationType == \"1\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn \"<font color='green'>Girdi</font>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t,\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"operationTime\"\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tstockMovementsTable.clear();\r\n");
      out.write("\t\t\t\t\tstockMovementsTable.rows.add(data);\r\n");
      out.write("\t\t\t\t\tstockMovementsTable.draw();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfillInventoryItemSelect = function(data){\r\n");
      out.write("\t\t\t\t$('#inventoryItemGroupCodeSelect').empty();\r\n");
      out.write("\t\t\t\tfor(var i = 0 ; i < data.length ; i++){\r\n");
      out.write("\t\t\t\t\tvar options = \"<option value='\"+data[i].id+\"' selected>\"+data[i].groupName+\"</option>\";\r\n");
      out.write("\t\t\t\t\t$('#inventoryItemGroupCodeSelect').append(options);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tgetStockMovements = function(){\r\n");
      out.write("\t\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\t\tjsonreq.params[0] = \"get_stock_movements\";\r\n");
      out.write("\t\t\t\tsendAjaxSI(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfillInventoryItemTable = function(data){\r\n");
      out.write("\t\t\t\tif(typeof inventoryItemTable == 'undefined'){\r\n");
      out.write("\t\t\t\t\tinventoryItemTable = $('#inventoryItemTable').DataTable({\r\n");
      out.write("\t\t\t\t\t\t\"language\": {\r\n");
      out.write("\t\t\t\t            \"lengthMenu\": \"Sayfa başına _MENU_ kayıt\",\r\n");
      out.write("\t\t\t\t            \"zeroRecords\": \"Nothing found - sorry\",\r\n");
      out.write("\t\t\t\t            \"info\": \"_PAGE_ sayfadan _PAGES_ gösteriliyor\",\r\n");
      out.write("\t\t\t\t            \"infoEmpty\": \"Data bulunamadı\",\r\n");
      out.write("\t\t\t\t            \"infoFiltered\": \"(filtered from _MAX_ total records)\",\r\n");
      out.write("\t\t\t\t            \"search\" : \"Arama\",\r\n");
      out.write("\t\t\t\t            \"paginate\": {\r\n");
      out.write("\t\t\t\t                \"previous\": \"Geri\",\r\n");
      out.write("\t\t\t\t                \"next\" : \"İleri\"\r\n");
      out.write("\t\t\t\t            }\r\n");
      out.write("\t\t\t\t        },\r\n");
      out.write("\t\t\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t\t\t\t\"columns\" : [\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"itemId\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"itemName\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"itemCode\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"groupName\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"itemQty\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"itemPrice\"\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tinventoryItemTable.clear();\r\n");
      out.write("\t\t\t\t\tinventoryItemTable.rows.add(data);\r\n");
      out.write("\t\t\t\t\tinventoryItemTable.draw();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#inventoryItemTable tbody').on('click', 'tr', function () {\r\n");
      out.write("\t\t\t\t\tif ($(this).hasClass('selectedRow') ) {\r\n");
      out.write("\t\t\t            $(this).removeClass('selectedRow');\r\n");
      out.write("\t\t\t            $('#updateInventoryItemButton').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t            $('#deleteInventoryItemButton').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t        } else {\r\n");
      out.write("\t\t\t        \tinventoryItemTable.$('tr.selectedRow').removeClass('selectedRow');\r\n");
      out.write("\t\t\t            $(this).addClass('selectedRow');\r\n");
      out.write("\t\t\t            var data = inventoryItemTable.row(this).data();\r\n");
      out.write("\t\t\t            currentRowDataInventoryItem = data;\r\n");
      out.write("\t\t\t            $('#updateInventoryItemButton').attr(\"disabled\",false);\r\n");
      out.write("\t\t\t            $('#deleteInventoryItemButton').attr(\"disabled\",false);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfillInventoryGroupTable = function(data){\r\n");
      out.write("\t\t\t\tif(typeof inventoryGroupTable == 'undefined'){\r\n");
      out.write("\t\t\t\t\tinventoryGroupTable = $('#inventoryGroupTable').DataTable({\r\n");
      out.write("\t\t\t\t\t\t\"language\": {\r\n");
      out.write("\t\t\t\t            \"lengthMenu\": \"Sayfa başına _MENU_ kayıt\",\r\n");
      out.write("\t\t\t\t            \"zeroRecords\": \"Nothing found - sorry\",\r\n");
      out.write("\t\t\t\t            \"info\": \"_PAGE_ sayfadan _PAGES_ gösteriliyor\",\r\n");
      out.write("\t\t\t\t            \"infoEmpty\": \"Data bulunamadı\",\r\n");
      out.write("\t\t\t\t            \"infoFiltered\": \"(filtered from _MAX_ total records)\",\r\n");
      out.write("\t\t\t\t            \"search\" : \"Arama\",\r\n");
      out.write("\t\t\t\t            \"paginate\": {\r\n");
      out.write("\t\t\t\t                \"previous\": \"Geri\",\r\n");
      out.write("\t\t\t\t                \"next\" : \"İleri\"\r\n");
      out.write("\t\t\t\t            }\r\n");
      out.write("\t\t\t\t        },\r\n");
      out.write("\t\t\t\t\t\tdata: data,\r\n");
      out.write("\t\t\t\t\t\t\"columns\" : [\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"id\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"groupName\"\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: \"groupCode\"\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tinventoryGroupTable.clear();\r\n");
      out.write("\t\t\t\t\tinventoryGroupTable.rows.add(data);\r\n");
      out.write("\t\t\t\t\tinventoryGroupTable.draw();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#inventoryGroupTable tbody').on('click', 'tr', function () {\r\n");
      out.write("\t\t\t\t\tif ($(this).hasClass('selectedRow') ) {\r\n");
      out.write("\t\t\t            $(this).removeClass('selectedRow');\r\n");
      out.write("\t\t\t            $('#updateInventoryGroup').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t            $('#deleteInventoryGroup').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t        } else {\r\n");
      out.write("\t\t\t        \tinventoryGroupTable.$('tr.selectedRow').removeClass('selectedRow');\r\n");
      out.write("\t\t\t            $(this).addClass('selectedRow');\r\n");
      out.write("\t\t\t            var data = inventoryGroupTable.row(this).data();\r\n");
      out.write("\t\t\t            currentRowDataInventoryGroup = data;\r\n");
      out.write("\t\t\t            $('#updateInventoryGroup').attr(\"disabled\",false);\r\n");
      out.write("\t\t\t            $('#deleteInventoryGroup').attr(\"disabled\",false);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tgetInventoryGroups = function(){\r\n");
      out.write("\t\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\t\tjsonreq.params[0] = \"get_inventory_groups\";\r\n");
      out.write("\t\t\t\tsendAjaxSI(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tgetInventoryItems = function(){\r\n");
      out.write("\t\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\t\tjsonreq.params[0] = \"get_inventory_items\";\r\n");
      out.write("\t\t\t\tsendAjaxSI(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#newInventoryGroup').on('click',function(){\r\n");
      out.write("\t\t\t\t$('#inventoryGroupIdInput').val('');\r\n");
      out.write("\t\t\t\t$('#inventoryGroupNameInput').val('');\r\n");
      out.write("\t\t\t\t$('#inventoryGroupCodeInput').val('');\r\n");
      out.write("\t\t\t\t$('#inventoryGroupModal').modal('show');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#updateInventoryGroup').on('click',function(){\r\n");
      out.write("\t\t\t\t$('#inventoryGroupIdInput').val(currentRowDataInventoryGroup.id);\r\n");
      out.write("\t\t\t\t$('#inventoryGroupNameInput').val(currentRowDataInventoryGroup.groupName);\r\n");
      out.write("\t\t\t\t$('#inventoryGroupCodeInput').val(currentRowDataInventoryGroup.groupCode);\r\n");
      out.write("\t\t\t\t$('#inventoryGroupModal').modal('show');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#deleteInventoryGroup').on('click',function(){\r\n");
      out.write("\t\t\t\tif(confirm(currentRowDataInventoryGroup.groupName + \" silinecek. Emin misiniz?\")){\r\n");
      out.write("\t\t\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\t\t\tjsonreq.params[0] = \"delete_inventory_group\";\r\n");
      out.write("\t\t\t\t\tjsonreq.params[1] = currentRowDataInventoryGroup.id;\r\n");
      out.write("\t\t\t\t\tsendAjaxSI(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#inventoryGroupSaveButton').on('click',function(){\r\n");
      out.write("\t\t\t\tvar groupObj = new Object();\r\n");
      out.write("\t\t\t\tif($('#inventoryGroupIdInput').val().length > 0){\r\n");
      out.write("\t\t\t\t\tgroupObj.id = $('#inventoryGroupIdInput').val();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tgroupObj.groupName = $('#inventoryGroupNameInput').val();\r\n");
      out.write("\t\t\t\tgroupObj.groupCode = $('#inventoryGroupCodeInput').val();\r\n");
      out.write("\t\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\t\tjsonreq.params[0] = \"save_inventory_group\";\r\n");
      out.write("\t\t\t\tjsonreq.params[1] = JSON.stringify(groupObj);\r\n");
      out.write("\t\t\t\tsendAjaxSI(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#newInventoryItemButton').on('click',function(){\r\n");
      out.write("\t\t\t\t$('#inventoryItemIdInput').val('');\r\n");
      out.write("\t\t\t\t$('#inventoryItemCodeInput').val('');\r\n");
      out.write("\t\t\t\t$('#inventoryItemNameInput').val('');\r\n");
      out.write("\t\t\t\t$('#inventoryItemGroupCodeSelect').prop(\"selectedIndex\", 0).trigger('change');\r\n");
      out.write("\t\t\t\t$('#inventoryItemQtyInput').val('');\r\n");
      out.write("\t\t\t\t$('#inventoryItemPriceInput').val('');\r\n");
      out.write("\t\t\t\t$('#inventoryItemModal').modal('show');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#updateInventoryItemButton').on('click',function(){\r\n");
      out.write("\t\t\t\t$('#inventoryItemIdInput').val(currentRowDataInventoryItem.itemId);\r\n");
      out.write("\t\t\t\t$('#inventoryItemCodeInput').val(currentRowDataInventoryItem.itemCode);\r\n");
      out.write("\t\t\t\t$('#inventoryItemNameInput').val(currentRowDataInventoryItem.itemName);\r\n");
      out.write("\t\t\t\t$('#inventoryItemGroupCodeSelect').val(currentRowDataInventoryItem.itemGroup).trigger('change');\r\n");
      out.write("\t\t\t\t$('#inventoryItemQtyInput').val(currentRowDataInventoryItem.itemQty);\r\n");
      out.write("\t\t\t\t$('#inventoryItemPriceInput').val(currentRowDataInventoryItem.itemPrice);\r\n");
      out.write("\t\t\t\t$('#inventoryItemModal').modal('show');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#deleteInventoryItemButton').on('click',function(){\r\n");
      out.write("\t\t\t\tif(confirm(currentRowDataInventoryItem.itemName + \" silinecek. Emin misiniz?\")){\r\n");
      out.write("\t\t\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\t\t\tjsonreq.params[0] = \"delete_inventory_item\";\r\n");
      out.write("\t\t\t\t\tjsonreq.params[1] = currentRowDataInventoryItem.itemId;\r\n");
      out.write("\t\t\t\t\tsendAjaxSI(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#inventoryItemSaveButton').on('click',function(){\r\n");
      out.write("\t\t\t\tvar itemObj = new Object();\r\n");
      out.write("\t\t\t\tif($('#inventoryItemIdInput').val().length > 0){\r\n");
      out.write("\t\t\t\t\titemObj.itemId = $('#inventoryItemIdInput').val();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\titemObj.itemCode = $('#inventoryItemCodeInput').val();\r\n");
      out.write("\t\t\t\titemObj.itemName = $('#inventoryItemNameInput').val();\r\n");
      out.write("\t\t\t\titemObj.itemGroup = $('#inventoryItemGroupCodeSelect').val();\r\n");
      out.write("\t\t\t\titemObj.itemQty = $('#inventoryItemQtyInput').val();\r\n");
      out.write("\t\t\t\titemObj.itemPrice = $('#inventoryItemPriceInput').val().replace(',','.');\r\n");
      out.write("\t\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\t\tjsonreq.params[0] = \"save_inventory_item\";\r\n");
      out.write("\t\t\t\tjsonreq.params[1] = JSON.stringify(itemObj);\r\n");
      out.write("\t\t\t\tsendAjaxSI(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tgetInventoryItems();\r\n");
      out.write("\t\t\tgetInventoryGroups();\r\n");
      out.write("\t\t\tgetStockMovements();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div style=\"margin-left:10px\">\r\n");
      out.write("\t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t<li class=\"nav-item waves-effect waves-light\">\r\n");
      out.write("\t\t\t\t<a class=\"nav-link active\"  data-toggle=\"tab\" href=\"#inventoryListTab\" role=\"tab\" aria-selected=\"true\">Envanter İşlemleri</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"nav-item waves-effect waves-light\">\r\n");
      out.write("\t\t\t\t<a class=\"nav-link\" data-toggle=\"tab\" href=\"#inventoryMovements\" role=\"tab\" aria-selected=\"false\">Stok Hareketleri</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("    \t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tab-content\">\r\n");
      out.write("\t\t<div class=\"tab-pane fade active show\" id=\"inventoryListTab\" role=\"tabpanel\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("    \t\t\t\tEnvanter Grupları\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<table id=\"inventoryGroupTable\" class=\"table table-hover\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Grup Adı</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Grup Kodu</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group\" role=\"group\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-success btn-sm\" id=\"newInventoryGroup\">Yeni Kayıt</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" id=\"updateInventoryGroup\" disabled>Düzenle</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-danger btn-sm\" id=\"deleteInventoryGroup\" disabled>Sil</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("    \t\t\t\tEnvanter Listesi\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<table id=\"inventoryItemTable\" class=\"table table-hover\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Ürün Adı</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Ürün Kodu</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Ürün Grubu</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Ürün Adedi</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Ürün Fiyatı</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group\" role=\"group\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-success btn-sm\" id=\"newInventoryItemButton\">Yeni Kayıt</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-sm\" id=\"updateInventoryItemButton\" disabled>Düzenle</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-danger btn-sm\" id=\"deleteInventoryItemButton\" disabled>Sil</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"tab-pane fade\" id=\"inventoryMovements\" role=\"tabpanel\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("    \t\t\t\tHareketler\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<table id=\"stockMovementsTable\" class=\"table table-hover\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Müşteri</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Ürün Grup Kodu</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Ürün Grubu</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Ürün Kodu</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Ürün Adı</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Miktar</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>İşlem</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Tarih</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"inventoryGroupModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-md\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\">Envanter Grubu Kayıt</h5>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"inventoryGroupIdInput\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\tGrup Adı:\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-controller\" id=\"inventoryGroupNameInput\" style=\"width:100%\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\tGrup Kodu:\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"form-controller\" id=\"inventoryGroupCodeInput\" style=\"width:100%\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-sm btn-success\" id=\"inventoryGroupSaveButton\">Kaydet</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"modal fade\" id=\"inventoryItemModal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-md\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\">Envanter Kayıt</h5>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"inventoryItemIdInput\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\tÜrün:\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"width:100%\" class=\"form-controller\" id=\"inventoryItemNameInput\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\tÜrün Kodu:\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"width:100%\" class=\"form-controller\" id=\"inventoryItemCodeInput\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\tÜrün Grubu:\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<select style=\"width:100%\" class=\"form-select\" id=\"inventoryItemGroupCodeSelect\"></select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\tÜrün Adedi:\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"width:100%\" type=\"number\" class=\"form-controller\" id=\"inventoryItemQtyInput\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\tÜrün Fiyatı:\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"width:100%\" type=\"number\" class=\"form-controller\" id=\"inventoryItemPriceInput\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\" style=\"background-color: #ECF0F1\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-sm btn-success\" id=\"inventoryItemSaveButton\">Kaydet</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- MAIN CONTENT START -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
