/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-27 18:40:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.accountingapp.service.AccountingService;
import com.accountingapp.model.User;

public final class headerandmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.accountingapp.model.User");
    _jspx_imports_classes.add("com.accountingapp.service.AccountingService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");

	User user = (User)request.getSession().getAttribute("currentUser");
	String userName = "";
	if(user == null){
		response.sendRedirect("/Accounting/login.jsp");
	} else {
		userName = user.getUserName() + " " + user.getUserSurname();
	}

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<title>Muhasebe Uygulaması</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"../include/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"../include/css/simple-sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"../include/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"../include/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.selectedRow {\r\n");
      out.write("\t\tbackground-color:#D0D3D4\r\n");
      out.write("\t}\r\n");
      out.write("\t#menuHeaderDiv{\r\n");
      out.write("\t\tcursor:pointer\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tvar setCookie;\r\n");
      out.write("\tvar getCookie;\r\n");
      out.write("\tvar setFrame;\r\n");
      out.write("\tvar lastPage;\r\n");
      out.write("\tvar currentUserName = \"");
      out.print(userName);
      out.write("\";\r\n");
      out.write("\tvar sendAjaxMP;\r\n");
      out.write("\tvar exit;\r\n");
      out.write("\tvar getUserMenu;\r\n");
      out.write("\tvar fillUserMenu;\r\n");
      out.write("\tvar loadPage;\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tsendAjaxMP = function(jsonreq,url,async,type){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\ttype : type,\r\n");
      out.write("\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\tdata : JSON.stringify(jsonreq),\r\n");
      out.write("\t\t\t\tcontentType : 'application/json',\r\n");
      out.write("\t\t\t\tmimeType : 'application/json',\r\n");
      out.write("\t\t\t\tasync : async,\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tif(data.includes(\"redirect_url\")){\r\n");
      out.write("\t\t\t\t\t\twindow.location.href = data.split(\":\")[1];\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tif(jsonreq.params[0] == \"get_user_menu\"){\r\n");
      out.write("\t\t\t\t\t\t\tfillUserMenu(data);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t            error : function(e){\r\n");
      out.write("\t            \talert('ERROR '+e.responseText)\r\n");
      out.write("\t            }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfillUserMenu = function(data){\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < data.length ; i++){\r\n");
      out.write("\t\t\t\tvar menuHtml = \"<a href='#' onclick='loadPage(\\\"\"+data[i].menuSrc+\"\\\");' class='list-group-item list-group-item-action bg-light'>\" + data[i].menuLabel + \"</a>\";\r\n");
      out.write("\t\t\t\t$('#mainPageMenuDiv').append(menuHtml);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar exitButton = '<a href=\"#\" onclick=\"exit();\" class=\"list-group-item list-group-item-action bg-light\" style=\"vertical-align:text-bottom\"><font color=\"#dc3545\">Çıkış</font></a>';\r\n");
      out.write("\t\t\t$('#mainPageMenuDiv').append(exitButton);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgetUserMenu = function(){\r\n");
      out.write("\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\tjsonreq.params[0] = \"get_user_menu\"\r\n");
      out.write("\t\t\tsendAjaxMP(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#currentUserLabel').html(currentUserName);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsetCookie = function(cname, cvalue, exdays){\r\n");
      out.write("\t\t\tvar d = new Date();\r\n");
      out.write("\t\t\td.setTime(d.getTime() + (exdays*24*60*60*1000));\r\n");
      out.write("\t\t\tvar expires = \"expires=\"+ d.toUTCString();\r\n");
      out.write("\t\t\tdocument.cookie = cname + \"=\" + cvalue + \";\" + expires + \";path=/\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\texit = function(){\r\n");
      out.write("\t\t\tvar jsonreq = new Object();\r\n");
      out.write("\t\t\tjsonreq.params = new Array();\r\n");
      out.write("\t\t\tjsonreq.params[0] = \"exit\";\r\n");
      out.write("\t\t\tsendAjaxMP(jsonreq,\"/Accounting/AccountingServlet\",false,\"POST\");\r\n");
      out.write("\t\t\twindow.location.href = \"/Accounting/login.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgetCookie = function(cname){\r\n");
      out.write("\t\t\tvar name = cname + \"=\";\r\n");
      out.write("\t\t\tvar decodedCookie = decodeURIComponent(document.cookie);\r\n");
      out.write("\t\t\tvar ca = decodedCookie.split(';');\r\n");
      out.write("\t\t\tfor(var i = 0; i <ca.length; i++) {\r\n");
      out.write("\t\t\t\tvar c = ca[i];\r\n");
      out.write("\t\t\t\twhile (c.charAt(0) == ' ') {\r\n");
      out.write("\t\t\t\t\tc = c.substring(1);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif (c.indexOf(name) == 0) {\r\n");
      out.write("\t\t\t\treturn c.substring(name.length, c.length);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tloadPage = function(src){\r\n");
      out.write("\t\t\twindow.location.href = src;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsetFrame = function(src){\r\n");
      out.write("\t\t\t$('#mainDiv').fadeOut(100,function(){\r\n");
      out.write("\t\t\t\t$('#mainDiv').load(src);\r\n");
      out.write("\t            $('#mainDiv').fadeIn(1000);\r\n");
      out.write("\t            setCookie(\"last_page\",src,100);\r\n");
      out.write("\t        });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*lastPage = getCookie(\"last_page\");\r\n");
      out.write("\t\tif(lastPage.length > 0){\r\n");
      out.write("\t\t\tsetFrame(lastPage);\r\n");
      out.write("\t\t}*/\r\n");
      out.write("\t\tgetUserMenu();\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"d-flex\" id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <div class=\"bg-light border-right\" id=\"sidebar-wrapper\">\r\n");
      out.write("      <div class=\"sidebar-heading\" id=\"menuHeaderDiv\" onclick=\"loadPage('./index.jsp')\"><b>AccountingApp</b> </div>\r\n");
      out.write("      <div class=\"list-group list-group-flush\" id=\"mainPageMenuDiv\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#sidebar-wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Content -->\r\n");
      out.write("    <div id=\"page-content-wrapper\">\r\n");
      out.write("\r\n");
      out.write("      <nav class=\"navbar navbar-expand-lg navbar-light bg-light border-bottom\">\r\n");
      out.write("\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("          <ul class=\"navbar-nav ml-auto mt-2 mt-lg-0\">\r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"#\"><label id=\"currentUserLabel\"></label> <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
